### ISSUE TITLE
Translation in english for the Faust community  ?

### ISSUE THREAD

**Issue by sletz** [LucaSpanedda/Digital_Reverberation_in_Faust#6]
This project seems quite interesting ((-;. Any plan to make is available for the Faust community as an english translated version ?

**Comment by LucaSpanedda** [comment]
Hi Stéphane, thankyou for the interest in the project. Soon as the first thing i will take care of making an English translation of the README file. Obviously the project still has a lot of imperfections and things to revise because I am alone working on these codes, but after the translation actually it could be open up to the Faust community, for create a space where people can contribute with resources for understand the digital reverberation and get down to the more complex models. :)

**Comment by sletz** [comment]
It would be great yes !

**Comment by LucaSpanedda** [comment]
Hi Stéphane,
Done! The repo is still a work in progress, but now everything is in English, and there are many reverberator models and features. From here on, it would be great to share it with the community, get feedback, and work together to fix bugs, improve documentation, and so on.

Additionally, there are several implementations that, if verified, could be interesting to push to the reverb section of the Faust libraries. For example, I've ported the Griesinger Lexicon algorithm (similar to Dattorro's), adapted Tom Erbe’s algorithm from PD, and also attempted a port of the Keith Barr allpass loop reverb directly from the open-source Spin-Assembly codes on the Spin Semiconductor website. The results are very promising! :)

**Comment by sletz** [comment]
Great contribution ! The documentation still have some typos and would need for some more formatting to make it more readable. 

Then to share with the community, can you possibly use the mailing list https://faust.grame.fr/community/help/#faust-mailing-lists and the Discord channel https://faust.grame.fr/community/help/#faust-on-discord ?
